# Site settings
title: Сергей Красноперов - Golang & python developer and DevOps
tag_text: Сергей Красноперов
description: Я бекенд разработчик из Калининграда, Россия

url: https://sergeykrasnoperov.me
enforce_ssl: sergeykrasnoperov.me

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
